services:
  db:
    image: pgvector/pgvector:pg16

    env_file: 
        - .env.postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./db/migrations/ledger.sql:/docker-entrypoint-initdb.d/ledger.sql:ro
      - ./features/views.sql:/docker-entrypoint-initdb.d/views.sql:ro


volumes:
  pgdata: